# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Layout/LineLength:
  AutoCorrect: true
  Max: 120

Style/Documentation:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoreMacros: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  Enabled: false
