require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb
    - vendor/**/*
    - bin/bundle
    - bin/rails
    - bin/rake
    - tmp/**/*

Layout/LineLength:
  Max: 120
  AutoCorrect: true

Metrics/BlockLength:
  Max: 50 # Allow up to 50 lines per block
  AllowedMethods:
    - describe
    - context
    - it

Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/Documentation:
  Enabled: false
