name: "market_watcher"

services:
  rails-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    env_file:
      - ../.env
    volumes:
    - ../..:/workspaces:cached
    command: sleep infinity
    shm_size: "1g"
    depends_on:
    - postgres
    - redis

  postgres:
    image: postgres:16.1
    restart: unless-stopped
    networks:
    - default
    volumes:
    - postgres-data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data:rw

volumes:
  postgres-data:
  redis-data:
