default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DATABASE_POOL", ENV.fetch("RAILS_MAX_THREADS", 5)) %>
  host: <%= ENV.fetch("DB_HOST", "127.0.0.1") %>
  username: <%= ENV.fetch("DB_USER", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "postgres") %>

development:
  <<: *default
  database: market_watcher_development

test:
  <<: *default
  database: market_watcher_test

production:
  primary: &primary_production
    <<: *default
    database: market_watcher_production
