default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: market_watcher_development

test:
  <<: *default
  database: market_watcher_test

production:
  primary: &primary_production
    <<: *default
    database: market_watcher_production
    username: market_watcher
    password: <%= ENV["MARKET_WATCHER_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: market_watcher_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: market_watcher_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: market_watcher_production_cable
    migrations_paths: db/cable_migrate
